/**
 * How much of a snapshot canvas's bitmap to actually paint, given how small the
 * card is on screen.
 *
 * ## The problem
 *
 * An unfocused card's snapshot canvas is a bitmap in world units — 160x45 cells
 * is 1280x720 of them — and the camera's CSS transform is what puts it on
 * screen. At a zoom of 0.05 the compositor is minifying that bitmap by 20x, and
 * it does that with a single bilinear tap and no mipmaps: each screen pixel
 * takes a weighted sample of four bitmap pixels out of the four hundred it
 * covers. Whichever four those happen to be decides the colour, so a page of
 * text turns into a sparkle of surviving pixels that shifts as you pan — the
 * mosaic you see zoomed out. Nothing about the bitmap is wrong; it is being
 * point-sampled.
 *
 * ## The fix
 *
 * Paint the bitmap at roughly the size it will be shown at, so the compositor
 * has almost nothing left to minify and every glyph has contributed ink to the
 * pixels it covers rather than to whichever four the sampler happened to pick.
 * It is the mipmap, generated by re-drawing rather than by filtering, and it
 * costs *less* memory rather than more: at one eighth scale a card's bitmap is
 * 1/64th the pixels. What re-drawing does not get for free is the *brightness*
 * of the text it averages — see `glyphGrowth`.
 *
 * ## Why powers of two, and why a floor
 *
 * Quantising means the bitmap is only resized when the zoom crosses an octave,
 * rather than on every wheel notch, and rounding *up* to the next octave means
 * the residual is always a minification between 0.5x and 1x — never a
 * magnification, which would be visibly soft.
 *
 * Powers of two also keep every grid row on a whole number of bitmap pixels:
 * `CELL_HEIGHT` is 16, so at the smallest level a row is exactly one pixel
 * tall. That is what lets `TerminalCard` keep repainting single changed rows
 * instead of the whole grid — a row's band never half-covers a pixel shared
 * with its neighbour. The floor exists for that reason as much as for
 * legibility: below 1/16 a row would stop landing on pixel boundaries.
 */
export const MIN_SNAPSHOT_LOD = 1 / 16

/**
 * Never paint more bitmap pixels than world units, even on a Retina display
 * where the card is zoomed in far enough to want them. That would sharpen
 * unfocused cards at 4x the memory per card, which is the wrong trade on a
 * canvas whose whole design is "hundreds of cards, most of them small".
 */
export const MAX_SNAPSHOT_LOD = 1

/**
 * Bitmap pixels to paint per world unit, for a card drawn at camera zoom
 * `zoom` on a display with `dpr` device pixels per CSS pixel.
 *
 * A non-finite or non-positive zoom reads as "unknown", and unknown takes the
 * full-resolution branch: a too-sharp card is a wasted repaint, a too-coarse
 * one is a visible defect.
 */
export function snapshotLod(zoom: number, dpr: number): number {
  const wanted = zoom * dpr
  if (!Number.isFinite(wanted) || wanted <= 0) return MAX_SNAPSHOT_LOD
  const octave = 2 ** Math.ceil(Math.log2(wanted))
  return Math.min(MAX_SNAPSHOT_LOD, Math.max(MIN_SNAPSHOT_LOD, octave))
}

/**
 * The grid rows a repaint of `changed` has to clear and redraw.
 *
 * One row wider on each side than the rows that actually changed, because a
 * glyph's antialiasing spills past the cell it belongs to — most visibly at a
 * low level of detail, where a row is one or two bitmap pixels tall and most of
 * a glyph's ink is spill. Clearing a changed row's band therefore erases part
 * of its neighbours, so the neighbours have to be redrawn too, and they have to
 * be cleared first or the redraw composites fresh ink over the ink already
 * there and the row creeps darker with every update.
 *
 * Returned sorted and without duplicates, clamped to `rowCount`.
 */
export function rowsToRepaint(changed: readonly number[], rowCount: number): number[] {
  const touched = new Set<number>()
  for (const y of changed) {
    for (let dy = -1; dy <= 1; dy++) {
      const row = y + dy
      if (row >= 0 && row < rowCount) touched.add(row)
    }
  }
  return [...touched].sort((a, b) => a - b)
}

/**
 * Extra glyph size at `lod`, as a multiple of the font's normal size, to put
 * back the ink a small bitmap throws away.
 *
 * Canvas2D blends a glyph's antialiasing coverage in sRGB space rather than in
 * light. A stem thinner than a bitmap pixel lands a fraction of the way from
 * background to foreground *in sRGB units*, which is a much smaller fraction of
 * the way in actual light, so the smaller the bitmap the more of the text's
 * brightness the blend discards. Measured against the full-size render's total
 * light, a card painted at one eighth keeps 86% of it and one at one sixteenth
 * keeps 65% — the step you see as a card going dark once the zoom settles and
 * the level of detail catches up.
 *
 * Growing the glyph is the lever with no side effect. Brightening the colour
 * clips, and washes coloured text — a green test line, a red error — toward
 * white exactly when colour is the only thing still legible. Drawing the glyph
 * twice doubles the per-glyph cost, which is what a repaint is made of. A
 * slightly larger glyph thickens its own stems, keeps its colour exactly, and
 * is free; the distortion only ever applies where the glyph is already far too
 * small to read as a shape.
 *
 * Linear in how many world units one bitmap pixel has to stand in for, which is
 * what the measurements fit: 1/60 per unit lands within a couple of percent of
 * the full-size render's light at every level from 1/2 down to 1/16, and is
 * exactly 1 at full size, so a card being looked at is painted as it always was.
 */
export const GLYPH_GROWTH_PER_LOST_UNIT = 1 / 60

export function glyphGrowth(lod: number): number {
  return 1 + (1 / lod - 1) * GLYPH_GROWTH_PER_LOST_UNIT
}
