/**
 * Resolving a heard name to a roster name.
 *
 * Speech-to-text hears "Heaven" when the user said "Evan", "Clare" for
 * "Claire", "Zach" for "Jack". Ported from Voice Operator's NameAliases.swift
 * (deleted in voiceop 548e981): two tables, both keyed by lowercased names.
 *
 * - `ALIAS_TO_CANONICAL`: a likely mishearing or homophone → the roster name it
 *   stands for. Generated from the roster with Double Metaphone plus homophone
 *   judgment; every alias maps to exactly one name.
 * - `PHONETIC_KEY`: a roster name → its Double Metaphone primary code. The
 *   registry never has two names with the same code assigned at once (no Dana
 *   alongside Dean), so a code identifies at most one assigned name. That is
 *   what lets `resolveName` fall back to it: a heard "Dean" can only mean the
 *   assigned "Diana" when Dean itself is not assigned.
 *
 * The tables carry "ruby", which is not in the roster; it is harmless, since a
 * name resolves only to one of the candidates passed in.
 */

/** Lowercased mishearing → lowercased roster name. */
const ALIAS_TO_CANONICAL: Readonly<Record<string, string>> = {
  'alivia': 'olivia',
  'behth': 'beth',
  'belah': 'bella',
  'bellah': 'bella',
  'belle': 'bella',
  'bethe': 'beth',
  'blaik': 'blake',
  'blaike': 'blake',
  'blayke': 'blake',
  'broono': 'bruno',
  'brunno': 'bruno',
  'brunoh': 'bruno',
  'calib': 'caleb',
  'cate': 'kate',
  'cayleb': 'caleb',
  'clair': 'claire',
  'clare': 'claire',
  'cloe': 'chloe',
  'clowie': 'chloe',
  'dafne': 'daphne',
  'dafnee': 'daphne',
  'dafny': 'daphne',
  'danah': 'dana',
  'daphnee': 'daphne',
  'dayna': 'dana',
  'deane': 'dean',
  'deen': 'dean',
  'dene': 'dean',
  'dianah': 'diana',
  'dianna': 'diana',
  'donna': 'dana',
  'dyana': 'diana',
  'eathan': 'ethan',
  'eisaac': 'isaac',
  'ema': 'emma',
  'emmah': 'emma',
  'emmuh': 'emma',
  'ethen': 'ethan',
  'ethin': 'ethan',
  'evann': 'evan',
  'evin': 'evan',
  'evon': 'evan',
  'eyevee': 'ivy',
  'feelix': 'felix',
  'felux': 'felix',
  'feona': 'fiona',
  'fionah': 'fiona',
  'fyona': 'fiona',
  'gemmah': 'gemma',
  'georj': 'george',
  'gorge': 'george',
  'graice': 'grace',
  'grantt': 'grant',
  'grase': 'grace',
  'graunt': 'grant',
  'grayce': 'grace',
  'haidi': 'heidi',
  'haizel': 'hazel',
  'harvee': 'harvey',
  'harvie': 'harvey',
  'harvy': 'harvey',
  'hazil': 'hazel',
  'hazl': 'hazel',
  'heaven': 'evan',
  'heidy': 'heidi',
  'hendry': 'henry',
  'hennry': 'henry',
  'henri': 'henry',
  'hidi': 'heidi',
  'iriss': 'iris',
  'irus': 'iris',
  'irys': 'iris',
  'isaak': 'isaac',
  'isac': 'isaac',
  'ivey': 'ivy',
  'ivie': 'ivy',
  'izaak': 'isaac',
  'jacque': 'jack',
  'jaik': 'jake',
  'jaike': 'jake',
  'jain': 'jane',
  'jaine': 'jane',
  'jak': 'jack',
  'jaspar': 'jasper',
  'jaspur': 'jasper',
  'jasspur': 'jasper',
  'jayke': 'jake',
  'jayne': 'jane',
  'jemma': 'gemma',
  'jemmah': 'gemma',
  'jona': 'jonah',
  'jonna': 'jonah',
  'joolia': 'julia',
  'jorge': 'george',
  'juliah': 'julia',
  'juliuh': 'julia',
  'kait': 'kate',
  'kaleb': 'caleb',
  'kayte': 'kate',
  'khloe': 'chloe',
  'kial': 'kyle',
  'kile': 'kyle',
  'klaire': 'claire',
  'knowlen': 'nolan',
  'kyel': 'kyle',
  'laurah': 'laura',
  'lawra': 'laura',
  'leeo': 'leo',
  'leoh': 'leo',
  'leone': 'leon',
  'leonn': 'leon',
  'leyon': 'leon',
  'lilee': 'lily',
  'lillie': 'lily',
  'lilly': 'lily',
  'lio': 'leo',
  'loagan': 'logan',
  'logen': 'logan',
  'login': 'logan',
  'loocas': 'lucas',
  'looke': 'luke',
  'loosey': 'lucy',
  'lora': 'laura',
  'louke': 'luke',
  'luccas': 'lucas',
  'lucey': 'lucy',
  'lucie': 'lucy',
  'luk': 'luke',
  'lukas': 'lucas',
  'macks': 'max',
  'maia': 'maya',
  'maison': 'mason',
  'maks': 'max',
  'mali': 'molly',
  'marc': 'mark',
  'marcas': 'marcus',
  'marck': 'mark',
  'marcous': 'marcus',
  'markk': 'mark',
  'markus': 'marcus',
  'masen': 'mason',
  'masun': 'mason',
  'maxx': 'max',
  'mayah': 'maya',
  'meah': 'mia',
  'meya': 'mia',
  'miah': 'mia',
  'mials': 'miles',
  'milez': 'miles',
  'mollee': 'molly',
  'molley': 'molly',
  'mollie': 'molly',
  'mya': 'maya',
  'myles': 'miles',
  'naithan': 'nathan',
  'naomie': 'naomi',
  'nathen': 'nathan',
  'nathin': 'nathan',
  'nayomi': 'naomi',
  'neena': 'nina',
  'neenah': 'nina',
  'neomi': 'naomi',
  'ninah': 'nina',
  'noa': 'noah',
  'noha': 'noah',
  'nolen': 'nolan',
  'nolin': 'nolan',
  'noora': 'nora',
  'norah': 'nora',
  'norra': 'nora',
  'nowah': 'noah',
  'olivea': 'olivia',
  'oliverr': 'oliver',
  'oliviah': 'olivia',
  'olivier': 'oliver',
  'olliver': 'oliver',
  'osccar': 'oscar',
  'oscer': 'oscar',
  'oskar': 'oscar',
  'penney': 'penny',
  'penni': 'penny',
  'pennie': 'penny',
  'phelix': 'felix',
  'pipor': 'piper',
  'pipper': 'piper',
  'pyper': 'piper',
  'rachael': 'rachel',
  'rachal': 'rachel',
  'raechel': 'rachel',
  'reata': 'rita',
  'reeta': 'rita',
  'ritah': 'rita',
  'roeland': 'roland',
  'rolland': 'roland',
  'roobie': 'ruby',
  'rooth': 'ruth',
  'rosse': 'ross',
  'rosé': 'rose',
  'rowland': 'roland',
  'rows': 'rose',
  'roz': 'ross',
  'roze': 'rose',
  'rubey': 'ruby',
  'rubie': 'ruby',
  'ruthe': 'ruth',
  'sadee': 'sadie',
  'sady': 'sadie',
  'saidie': 'sadie',
  'saydee': 'sadie',
  'scot': 'scott',
  'scottt': 'scott',
  'simen': 'simon',
  'simmon': 'simon',
  'skott': 'scott',
  'stela': 'stella',
  'stellah': 'stella',
  'stellar': 'stella',
  'symon': 'simon',
  'tesa': 'tessa',
  'tessah': 'tessa',
  'tessuh': 'tessa',
  'vicktor': 'victor',
  'victer': 'victor',
  'viktor': 'victor',
  'vincant': 'vincent',
  'vincint': 'vincent',
  'vinsent': 'vincent',
  'vivan': 'vivian',
  'vivianne': 'vivian',
  'vivien': 'vivian',
  'waid': 'wade',
  'waide': 'wade',
  'wayde': 'wade',
  'wendey': 'wendy',
  'wendi': 'wendy',
  'wendie': 'wendy',
  'weslee': 'wesley',
  'wesly': 'wesley',
  'wezley': 'wesley',
  'wiatt': 'wyatt',
  'wyat': 'wyatt',
  'wyeth': 'wyatt',
  'yonah': 'jonah',
  'zach': 'jack',
  'zoey': 'zoe',
  'zoie': 'zoe',
  'zooey': 'zoe',
}

/** Lowercased roster name → Double Metaphone primary code. */
const PHONETIC_KEY: Readonly<Record<string, string>> = {
  bella: 'PL',
  beth: 'P0',
  blake: 'PLK',
  bruno: 'PRN',
  caleb: 'KLP',
  chloe: 'KL',
  claire: 'KLR',
  dana: 'TN',
  daphne: 'TFN',
  dean: 'TN',
  diana: 'TN',
  emma: 'AM',
  ethan: 'A0N',
  evan: 'AFN',
  felix: 'FLKS',
  fiona: 'FN',
  gemma: 'JM',
  george: 'JRJ',
  grace: 'KRS',
  grant: 'KRNT',
  harvey: 'HRF',
  hazel: 'HSL',
  heidi: 'HT',
  henry: 'HNR',
  iris: 'ARS',
  isaac: 'ASK',
  ivy: 'AF',
  jack: 'JK',
  jake: 'JK',
  jane: 'JN',
  jasper: 'JSPR',
  jonah: 'JN',
  julia: 'JL',
  kate: 'KT',
  kyle: 'KL',
  laura: 'LR',
  leo: 'L',
  leon: 'LN',
  lily: 'LL',
  logan: 'LKN',
  lucas: 'LKS',
  lucy: 'LS',
  luke: 'LK',
  marcus: 'MRKS',
  mark: 'MRK',
  mason: 'MSN',
  max: 'MKS',
  maya: 'M',
  mia: 'M',
  miles: 'MLS',
  molly: 'ML',
  naomi: 'NM',
  nathan: 'N0N',
  nina: 'NN',
  noah: 'N',
  nolan: 'NLN',
  nora: 'NR',
  oliver: 'ALFR',
  olivia: 'ALF',
  oscar: 'ASKR',
  penny: 'PN',
  piper: 'PPR',
  rachel: 'RXL',
  rita: 'RT',
  roland: 'RLNT',
  rose: 'RS',
  ross: 'RS',
  ruby: 'RP',
  ruth: 'R0',
  sadie: 'ST',
  scott: 'SKT',
  simon: 'SMN',
  stella: 'STL',
  tessa: 'TS',
  victor: 'FKTR',
  vincent: 'FNSNT',
  vivian: 'FFN',
  wade: 'AT',
  wendy: 'ANT',
  wesley: 'ASL',
  wyatt: 'AT',
  zoe: 'S',
}

/** Resolve one lowercased word to the candidate it names, if any. */
function resolveWord(word: string, candidates: readonly string[]): string | undefined {
  const canonical = ALIAS_TO_CANONICAL[word] ?? word
  const exact = candidates.find((c) => c.toLowerCase() === canonical)
  if (exact !== undefined) return exact
  const key = PHONETIC_KEY[canonical]
  if (key === undefined) return undefined
  const soundAlikes = candidates.filter((c) => PHONETIC_KEY[c.toLowerCase()] === key)
  return soundAlikes.length === 1 ? soundAlikes[0] : undefined
}

/**
 * The candidate name that `heard` refers to, or undefined if none.
 *
 * `candidates` are the names currently assigned (`NameRegistry.assignedNames()`);
 * the result is one of them, exactly as passed. Matching is case-insensitive and
 * tries, for each word: the word itself, its alias, then a unique candidate that
 * sounds the same (shares a phonetic key).
 *
 * `heard` may be a phrase: its words are tried left to right and the first that
 * resolves wins, so pass the part of the utterance that should be a name —
 * "Mark" in "tell Mark …" is a name, but so is "mark" in "mark it done".
 */
export function resolveName(heard: string, candidates: readonly string[]): string | undefined {
  const words = heard.normalize('NFC').toLowerCase().match(/\p{L}+/gu) ?? []
  for (const word of words) {
    const match = resolveWord(word, candidates)
    if (match !== undefined) return match
  }
  return undefined
}

/** A roster name's phonetic key (Double Metaphone primary code), case-insensitively. */
export function phoneticKey(name: string): string | undefined {
  return PHONETIC_KEY[name.toLowerCase()]
}

/** Every alias and the lowercased roster name it resolves to. For tests. */
export function aliasEntries(): ReadonlyArray<readonly [alias: string, canonical: string]> {
  return Object.entries(ALIAS_TO_CANONICAL)
}
