/**
 * Which roster names sound alike.
 *
 * Each roster name's Double Metaphone primary code, ported from Voice
 * Operator's NameAliases.swift (deleted in voiceop 548e981). The registry never
 * assigns two names with the same code at once — no Dana alongside Dean — so
 * no two agents on the canvas can be confused by ear, by the user or by the
 * model reading a dictated transcript.
 */

/** Lowercased roster name → Double Metaphone primary code. */
const PHONETIC_KEY: Readonly<Record<string, string>> = {
  bella: 'PL',
  beth: 'P0',
  blake: 'PLK',
  bruno: 'PRN',
  caleb: 'KLP',
  chloe: 'KL',
  claire: 'KLR',
  dana: 'TN',
  daphne: 'TFN',
  dean: 'TN',
  diana: 'TN',
  emma: 'AM',
  ethan: 'A0N',
  evan: 'AFN',
  felix: 'FLKS',
  fiona: 'FN',
  gemma: 'JM',
  george: 'JRJ',
  grace: 'KRS',
  grant: 'KRNT',
  harvey: 'HRF',
  hazel: 'HSL',
  heidi: 'HT',
  henry: 'HNR',
  iris: 'ARS',
  isaac: 'ASK',
  ivy: 'AF',
  jack: 'JK',
  jake: 'JK',
  jane: 'JN',
  jasper: 'JSPR',
  jonah: 'JN',
  julia: 'JL',
  kate: 'KT',
  kyle: 'KL',
  laura: 'LR',
  leo: 'L',
  leon: 'LN',
  lily: 'LL',
  logan: 'LKN',
  lucas: 'LKS',
  lucy: 'LS',
  luke: 'LK',
  marcus: 'MRKS',
  mark: 'MRK',
  mason: 'MSN',
  max: 'MKS',
  maya: 'M',
  mia: 'M',
  miles: 'MLS',
  molly: 'ML',
  naomi: 'NM',
  nathan: 'N0N',
  nina: 'NN',
  noah: 'N',
  nolan: 'NLN',
  nora: 'NR',
  oliver: 'ALFR',
  olivia: 'ALF',
  oscar: 'ASKR',
  penny: 'PN',
  piper: 'PPR',
  rachel: 'RXL',
  rita: 'RT',
  roland: 'RLNT',
  rose: 'RS',
  ross: 'RS',
  ruby: 'RP',
  ruth: 'R0',
  sadie: 'ST',
  scott: 'SKT',
  simon: 'SMN',
  stella: 'STL',
  tessa: 'TS',
  victor: 'FKTR',
  vincent: 'FNSNT',
  vivian: 'FFN',
  wade: 'AT',
  wendy: 'ANT',
  wesley: 'ASL',
  wyatt: 'AT',
  zoe: 'S',
}

/** A roster name's phonetic key (Double Metaphone primary code), case-insensitively. */
export function phoneticKey(name: string): string | undefined {
  return PHONETIC_KEY[name.toLowerCase()]
}
